### ISSUE TITLE
Add cancel button to create game screen

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#102]
#### Carried over from #23 
- [x] add a cancel button in appbar that: 
  - [x] deletes newGameViewModel data in gameservice
  - [x] pops back to lobby on tap 

![create a game - 2](https://user-images.githubusercontent.com/49229277/91064040-174ffe00-e672-11ea-85aa-f176183e122d.png)

#### Clean up leftovers? 
- [x] change title to "Create game 1/2" 
- [ ] make "eye" icon button switch between hide password text and show password text (and switch icon) 
- [x] ? change all uses of "new game" to "create game"

**Comment by nickmeinhold** [comment]
@tamari-gray just looking at what I missed in #23 again, I added a couple of subtasks to the issue (under "Clean up leftovers?" in main comment) - are you happy for these to be a part of this issue?

**Comment by nickmeinhold** [comment]
One more thing (sorry!) I've realised I've used "newGame" in some places and "createGame" in others... are you happy for me to go through and make it consistent? I'm thinking use createGame everywhere...

**Comment by tamari-gray** [comment]
Yes please I like create game alot better too!
