### ISSUE TITLE
Consider replacing top level object with top level method, static method or named constructor

### ISSUE THREAD

**Issue by nickmeinhold** [tamari-gray/niira#118]
@tamari-gray hey mate!  I saw this come through and thought it was worth discussing - in the last PR, based on my suggestion you changed the function `gamesInorderOfDistance` that returned some mock data to a top level object: 

[60 calculate distance between game and user by tamari-gray · Pull Request #94 · tamari-gray/niira](https://github.com/tamari-gray/niira/pull/94/commits/605d3789c765b02094ca00e447d60e956cc30e89)

I've used that pattern a bit in the past but I decided it was worth avoiding because it means you are always accessing the same object wherever you use it and there is the potential to change the object's members and so mess up later tests.  Happy to discuss if I'm not making sense! 👍

**Comment by tamari-gray** [comment]
thanks nick! completely agree. didn't consider that when i changed it.
The tests are updating the mock data so it will cause problems further
along, Ill make a small ticket to change her up :)

**Comment by nickmeinhold** [comment]
Closing as #119 was created to address this, @tamari-gray I just wanted to "close the loop", obviously please feel free to re-open or anything if you didn't want this closed. Thanks!

**Comment by tamari-gray** [comment]
Thank you! Sorry I didn't see that you made this an issue, I only saw the email and made #119 😅 Thanks for bringing it up anyway!

**Comment by nickmeinhold** [comment]
Oh I see, that makes sense!  No worries mate, thanks for your response 👍
