### ISSUE TITLE
Lobby: player join a game

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#21]
- requires #56 

#observe lobby screen

- [x] get + listen to created games from firebase
- [x] redirect to password page => input password to enter game
  - [x] back button to lobby screen
  - [x] form validation
  - [x] route to waiting screen on success

<img width="476" alt="Screen Shot 2020-08-20 at 9 45 28 pm" src="https://user-images.githubusercontent.com/1059276/90766220-8d7cf980-e32e-11ea-9026-40fdf6511b9e.png">

**Comment by nickmeinhold** [comment]
Woohoo!  Next project!

**Comment by nickmeinhold** [comment]
@tamari-gray where are the user flows again?  Would it be worth adding them to the wiki do you think?  I'm happy to do it if you think it's not a bad idea?

**Comment by nickmeinhold** [comment]
While I think of it - can I be annoying and ask you to give the XD file a name?  The "Untitled" always grabs my attention when I am looking through XD files... 

<img width="716" alt="Screen Shot 2020-08-20 at 9 52 16 pm" src="https://user-images.githubusercontent.com/1059276/90767024-ce294280-e32f-11ea-9f6f-5192d043a360.png">

Just if you don't mind of course, thanks mate!

**Comment by tamari-gray** [comment]
> @tamari-gray where are the user flows again? Would it be worth adding them to the wiki do you think? I'm happy to do it if you think it's not a bad idea?

yes please!
https://docs.google.com/document/d/1aUQN0n6Rcyge-gzOoopNITyyjJwS_kaJZC37AHhjxvs/edit?usp=sharing

**Comment by tamari-gray** [comment]
thanks for the quick response!
