### ISSUE TITLE
admin start game

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#26]
**quiting game forces all joined players to quit**
- [x] check if user is admin: get game.admin id + authservice.userId => check if same then give user admin privilages 

- [x] create AdminQuitCreatingGame bool in game object
- [x] make waitingForGameToStartScreen listen to streamOfJoinedGame =>
- [x] when admin quits, make AdminQuitCreatingGame() fn in database service => sets AdminQuitCreatingGame: true in fb
- [ ] 

- [x] show start game fab if user is admin 
- if tagger is chosen => confirmation dialog => navigation to playingGame
- if no tagger is chosen =>pop toast "please choose tagger first"

- [ ] update taggerTile to be light orange color

![admin start game – 1](https://user-images.githubusercontent.com/49229277/89396746-47327280-d752-11ea-82f7-31ebf59fffa4.png)
![admin start game – 2](https://user-images.githubusercontent.com/49229277/89396748-48639f80-d752-11ea-90ee-b38210ad97d5.png)
![admin start game – 3](https://user-images.githubusercontent.com/49229277/89396750-48fc3600-d752-11ea-987a-00d89fc6ccfe.png)

**Comment by tamari-gray** [comment]
no rush at all on this @nickmeinhold, scope is next 2 weeks to get around to it 🙏

**Comment by nickmeinhold** [comment]
hey mate whenever it suits you, could we schedule a quick session to get me up to speed?  I've forgotten a lot of how it all fits together

**Comment by tamari-gray** [comment]
sorry @nickmeinhold just sawur comment!

**Comment by tamari-gray** [comment]
keen as tommorow night sometime :)

**Comment by nickmeinhold** [comment]
OK great! 👍
