### ISSUE TITLE
create account with firebase

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#27]
- [x] create account in firebase on submit validated create account
 - [x] show snackbar if error + "please try again"

**Comment by nickmeinhold** [comment]
hey mate, couldn’t help myself and had a look at the firebase changes, these might be helpful: 

[Updates on Flutter and Firebase. Updated Firebase plugins for higher… | by Chris Sells | Flutter | Aug, 2020 | Medium](https://medium.com/flutter/updates-on-flutter-and-firebase-8076f70bc90e)

[FlutterFire Roadmap · Issue #2582 · FirebaseExtended/flutterfire](https://github.com/FirebaseExtended/flutterfire/issues/2582)

[Migration Guide | FlutterFire](https://flutter-firebase-docs.web.app/docs/migration/)

**Comment by nickmeinhold** [comment]
https://firebase.flutter.dev/docs looks great! 

"No more reading the native Android or web Firebase docs and using that to guess the equivalent APIs to use in your Flutter apps!"

We were just talking about that before we accidentally started the migration!

**Comment by tamari-gray** [comment]
closed with #45
