### ISSUE TITLE
handle auth state changed

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#31]
- [ ] setup provider to listen to onauthstatechanged stream
- [ ] if logged in observe lobby screen, else: create account screen

**Comment by nickmeinhold** [comment]
One option could be: 
- add a `Future<UserData> get streamOfAuthState` getter to the `AuthService` (I should have included that already sorry) 
- get the service from the provider (or maybe just use the service as we'll already have access to it where we are wanting to get it from the provider, ie. almost at the top of the widget tree) 
- get the stream from the service and use it in a StreamBuilder 
- build either the "lobby screen" or "create account screen" depending on what is emitted 

Shall I have a go at what I'm suggesting and see what you think?

**Comment by nickmeinhold** [comment]
On it!

**Comment by tamari-gray** [comment]
yes please nick!
that way sounds good, weve already got the service through provider so miles while access it there!

**Comment by tamari-gray** [comment]
wow that was really quick, thank you!!
