### ISSUE TITLE
navigate between auth screens

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#42]
navigate between create account and sign in via some state so when we pop after a successfull sign in it will always go back to the original material app

**Comment by nickmeinhold** [comment]
hey mate, I'm not sure if I understood the problem but I wondered if using [pushReplacement](https://api.flutter.dev/flutter/widgets/Navigator/pushReplacement.html) to navigate between create account and sign in might solve the problem you're seeing?  

I don't see anything wrong with setting state and rebuilding in this case, just had the thought and wanted to pass it on. Thanks!

**Comment by tamari-gray** [comment]
thats perfect 😍 thanks @nickmeinhold!
