### ISSUE TITLE
allow getting user location

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#55]
- [x] choose a package 
- [x] location service 
- [x] listen to stream and save latest value 
- [x] provide a function that returns a Future with the latest location

**Comment by nickmeinhold** [comment]
@tamari-gray I would say there are two good options (the two location plugins that are "Flutter Favourites") 
- [location | Flutter Package](https://pub.dev/packages/location) 
- [geolocator | Flutter Package](https://pub.dev/packages/geolocator) 

I've used geolocator and found it very good. It looks like it's slightly more active at this stage but not by much. Personally I think either would be fine.
