### ISSUE TITLE
set up project with firebase

### ISSUE THREAD

**Issue by tamari-gray** [tamari-gray/niira#6]
create new firebase project
 - make new email? 

Potential subtasks 
- [x] (tamari) create a firebase project 
- [x] (tamari) add nick [as a collaborator](https://stackoverflow.com/questions/37569460/how-to-add-collaborators-to-a-firebase-app) 
- [x] create an android app and download credentials file 
- [x] create an ios app and download credentials file 
- [ ] add credentials files to project and add to .gitignore 
  - [ ] android 
  - [x] ios 
- [x] enable email authentication 
- [ ] add note to README on how to add credential files to project

**Comment by nickmeinhold** [comment]
Hey mate!  Could you tell me a bit more about the task?  Is this to setup firebase auth?  Or the firebase project from the beginning?  Maybe both?  

Did you want me to do this or you want to discuss it?  

Great to be getting the ball rolling man!  :-)

**Comment by tamari-gray** [comment]
sorry kinda half ass did this ticket before going to sleep lol, are you free tommorow to have a little discussion? 
its to set up firebase/ auth, so we can both access the firebase console, thanks nick :)

**Comment by nickmeinhold** [comment]
No worries!  Yeah I'm free all day at this stage I think, definitely up for a chat!  

I'll have a go at breaking out the task into some subtasks and see what you think.

**Comment by tamari-gray** [comment]
sweet thanks for the sub tasks! ill try call around 3pm if it suits :)

**Comment by nickmeinhold** [comment]
Definitely!  Talk to you then 👍

**Comment by tamari-gray** [comment]
@nickmeinhold really sorry can I push to after 5pm. My uncle has an appointment at 3 and it might be a bit too loud.

**Comment by nickmeinhold** [comment]
Yeah no worries!  Catch you then

**Comment by tamari-gray** [comment]
thank you!

**Comment by nickmeinhold** [comment]
hijacking the thread slightly: what flutter channel are you on?  and is that the one you want for the project?  I can ask you about this when we talk later, just popped into my head caus I was dealing with channel issues all morning

**Comment by nickmeinhold** [comment]
I created a draft PR with the changes for iOS, thinking you could add whatever you want to it from the android side or whatever else
