### ISSUE TITLE
Move mocks folder into test directory

### ISSUE THREAD

**Issue by nickmeinhold** [tamari-gray/niira#64]
@tamari-gray hey mate, I didn't notice when we were working on this last sorry or I could have discussed it with you then, I suggest that the mocks be moved into the `test` dir for now and as we need mocks for the integration tests we create them in `test_driver` - it's a weird one, terrible for code reuse but arguably different enough contexts to have different classes anyway and you get a lot of benefits - the autocomplete will work being the big one I think... what do you reckon?  If you agree I'm happy to put up a PR.  Thanks!

**Comment by tamari-gray** [comment]
yes please nick!
you won me over with the autocomplete haha, and what was that spanish word for lets worry about it tommorw? cause ill just worry about integration tests when they come 😄

**Comment by nickmeinhold** [comment]
Mañana!
