### ISSUE TITLE
Use NavigationService for all navigation

### ISSUE THREAD

**Issue by nickmeinhold** [tamari-gray/niira#82]
**Is your feature request related to a problem? Please describe.**
If all navigation goes through the NavigationService it will be a lot easier to make any required changes down the track.  

**Describe the solution you'd like**
Have functions in the NavigationService that perform navigation and use Provider to access the service everywhere we do navigation.  

Questions 
- [x] @tamari-gray do you want the NavigationService to be named something else to make it clearer that it's more an odd cousin of a service than a service?

**Comment by tamari-gray** [comment]
yeah if you think its a good idea :)
I still dont super understand why its not a service like the auth or db services, super happy for the rename, could you please expand on how you define a service? 🙏

**Comment by nickmeinhold** [comment]
Yeah sorry man, I might not even be using "service" in a standard way - my idea of a service comes from working with Angular, but the definition there was pretty loose - from the [docs](https://angular.io/guide/architecture-services): 
> Service is a broad category encompassing any value, function, or feature that an app needs. A service is typically a class with a narrow, well-defined purpose. It should do something specific and do it well. 

The services we've created so far all "do something specific" which is to wrap a plugin (FirebaseAuth, Firestore, Geolocator) and that is the only dependency (at least it should be, I think I might make a ticket to remove the navigation service from the auth service now I think about it) 

I guess the NavigationService is basically doing the same thing, it kind of wraps the navigator - the main thing that makes it feel different to me is that it depends on flutter, so if it's a service it breaks the clean architecture dependency rules "Source code dependencies must point only inward, toward higher-level policies." (see [The Clean Architecture Dependency Rule](https://www.informit.com/articles/article.aspx?p=2832399)) because services are at a lower level than the UI. 

Probably not a very good explanation, but it helped me understand where I was coming from so thanks!  

Maybe we could just remove the Service and call it `Navigation`?  If my lifelong obsession with naming is taking up too much time I'm OK with being told to just get over it :-) 

Thanks!

**Comment by tamari-gray** [comment]
awesome super happy for it to be called navigation
