### ISSUE TITLE
Remove NavigationService from AuthService 

### ISSUE THREAD

**Issue by nickmeinhold** [tamari-gray/niira#83]
@tamari-gray this is meant as a discussion issue 
- I have setup the auth service to depend on the navigation service, which 
  - makes it a it cleaner than detecting errors in the widgets and calling the navigation service from there 
  - adds an extra dependency and complexity to the service 

This is an architecture question I guess and probably warrants a longer discussion over video chat. But also reasonable to just put it aside for later or just decide it's fine as is and stop analysing. I just wanted to make a placeholder so we can decide.  

Thanks!

**Comment by tamari-gray** [comment]
Thanks @nickmeinhold! Keen to discuss it tonight!

**Comment by nickmeinhold** [comment]
hey mate, was just issue hunting and saw this - do you remember where we got to on this?  Do you plan on moving to Navigator2?

**Comment by tamari-gray** [comment]
hey @nickmeinhold not sure where we got too on this but im happy to leave the auth service as is, and im planning to go to navigator 2 after i reach mvp :)

thanks for asking, it feels good to deal with the issue instead of  ignore it everytime i see it 😅

**Comment by nickmeinhold** [comment]
OK great, thanks!

**Comment by tamari-gray** [comment]
thanks for closing it :)
